In [1]:
# Importar librerias
import os
import pandas as pd
import glob

In [ ]:
# Configurar pandas para mostrar todas las columnas
pd.set_option('display.max_columns', None)

# 1. Ruta del archivo
ruta_Archivo = r'D:\crist\OneDrive\Estudios\Proyectos Para GitHub\avian-data-ml-pipeline\data\raw\AlimentoFabricado\ALIMENTOENERO2026.xls'

# 2. Leer el archivo con manejo de errores
try:
    # Leemos la pestaña correcta
    df_Alimento = pd.read_excel(ruta_Archivo, sheet_name='Datos')
    print(f"✅ Archivo leído correctamente: {ruta_Archivo}")
    print(f"📊 Total de filas cargadas: {len(df_Alimento)}\n")
    
    # 3. Ver los resultados (solo se ejecuta si el paso anterior funcionó)
    print("--- Información del DataFrame ---")
    df_Alimento.info()

    print("\n--- Primeras filas del DataFrame ---")
    display(df_Alimento.head())  # Usamos display para que se vea como tabla en Jupyter

except Exception as e:
    # Usamos ruta_Archivo en vez de df_Alimento para evitar el NameError
    print(f"❌ Error al intentar leer el archivo en {ruta_Archivo}: {e}")

✅ Archivo leído correctamente: D:\crist\OneDrive\Estudios\Proyectos Para GitHub\avian-data-ml-pipeline\data\raw\AlimentoFabricado\ALIMENTOENERO2026.xls
📊 Total de filas cargadas: 5570

--- Información del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5570 entries, 0 to 5569
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fcha             5570 non-null   datetime64[ns]
 1   Efectiva         5570 non-null   datetime64[ns]
 2   Hora             5570 non-null   object
 3   Núm tran         5570 non-null   int64
 4   Program          5565 non-null   object
 5   ID del Usuario   5570 non-null   object
 6   Tipo Trans       5570 non-null   object
 7   Orden            4678 non-null   object
 8   Lín.             5570 non-null   int64
 9   Observs          0 non-null      float64
 10  Ventas/Trabajo   5 non-null      object
 11  ID               5190 non-null   object
 12  Dirección        63 non-null     object
 13  Lín Producto     5570 non-null   int64
 14  Numero articulo  5570 non-null   object
 15  Descripción      5570 non-null   object
 16  UM               5570 non-null   object
 17  Cnt Requerd      5570 non-null   float64
 18  Cantidad         5570 non-null   float64
 19  Prec             5570 non-null   float64
 20  Moneda           5570 non-null   object
 21  PxQ              5570 non-null   float64
 22  Monto Contable   5570 non-null   int64
 23  CuMaterial       5570 non-null   float64
 24  Lote/Serie       760 non-null    object
 25  Referencia       0 non-null      float64
 26  Almacén          5570 non-null   object
 27  Ubicación        5190 non-null   object
 28  Peso Embarq      5570 non-null   int64
 29  Peso Neto        5570 non-null   int64
 30  CE180            5570 non-null   float64
 31  Site Origen      206 non-null    object
 32  Ubic Origen      206 non-null    object
dtypes: datetime64[ns](2), float64(8), int64(6), object(17)
memory usage: 1.4+ MB

--- Primeras filas del DataFrame ---

,Fcha,Efectiva,Hora,Núm tran,Program,ID del Usuario,Tipo Trans,Orden,Lín.,Observs,Ventas/Trabajo,ID,Dirección,Lín Producto,Numero articulo,Descripción,UM,Cnt Requerd,Cantidad,Prec,Moneda,PxQ,Monto Contable,CuMaterial,Lote/Serie,Referencia,Almacén,Ubicación,Peso Embarq,Peso Neto,CE180,Site Origen,Ubic Origen
0,2026-01-31,2026-01-31,12:50:00,28403130,iclotr02.p,rpalomin,RCT-TR,NaN,0,NaN,NaN,403129*,NaN,7,1325,Mycofix plus,kg,0.0,1000.0,4871.000000,CLP,4871000.0,4871000,4895.075595,LS-BI00002091,NaN,PIFCA,PIFCA,0,1,0.0,CINTA,TRANSITO
1,2026-01-31,2026-01-31,12:50:00,28403129,iclotr02.p,rpalomin,ISS-TR,NaN,0,NaN,NaN,403129*,NaN,7,1325,Mycofix plus,kg,0.0,-1000.0,4871.000000,CLP,-4871000.0,4871000,4871.000000,LS-BI00002091,NaN,CINTA,TRANSITO,0,1,0.0,NaN,NaN
2,2026-01-31,2026-01-31,12:50:00,28403128,iclotr02.p,rpalomin,CST-ADJ,NaN,0,NaN,NaN,NaN,NaN,7,1325,Mycofix plus,kg,1000.0,0.0,0.000000,CLP,0.0,0,5203.168699,NaN,NaN,PIFCA,NaN,0,1,0.0,NaN,NaN
3,2026-01-31,2026-01-31,12:39:59,28403127,iclotr02.p,rpalomin,RCT-TR,NaN,0,NaN,NaN,403126*,NaN,15,PICHALMTO,Almto Pichidegua POSTURA,KG,0.0,3100.0,260.209032,CLP,806648.0,806648,266.406323,PICH5ACO,NaN,PICH5ACO,PIFCA,0,1,0.0,PIFCA,PIFCA
4,2026-01-31,2026-01-31,12:39:59,28403126,iclotr02.p,rpalomin,ISS-TR,NaN,0,NaN,NaN,403126*,NaN,15,PICHALMTO,Almto Pichidegua POSTURA,KG,0.0,-3100.0,260.209032,CLP,-806648.0,806648,260.209032,PICH5ACO,NaN,PIFCA,PIFCA,0,1,0.0,NaN,NaN

Dejar solamente las columnas a utilizar o utiles

In [6]:
# 1. Definir una lista con los nombres de las columnas que necesitams
columnas_utiles = [
    'Efectiva',
    'Tipo Trans',
    'Orden',
    'Lín Producto',
    'Numero articulo',
    'Descripción',
    'UM',
    'Cnt Requerd',
    'Cantidad',
    'Lote/Serie',
    'Almacén',
    'Ubicación'
]

# 2. Aplicar el filtro al DataFrame
# Usar .copy() para crear un DataFrema indenepdiente y evitar la advertencia 'SettingWithCopyWarning' de Pandas
df_alimento_limpio = df_Alimento[columnas_utiles].copy()

# 3. Validar resultado
print(f"✅ Reducción exitosa: Pasamos de {len(df_Alimento.columns)} columnas a solo {len(df_alimento_limpio.columns)}.")
print("--- Nueva estructura del DataFrame ---")
display(df_alimento_limpio.head(10))

✅ Reducción exitosa: Pasamos de 33 columnas a solo 12.
--- Nueva estructura del DataFrame ---

,Efectiva,Tipo Trans,Orden,Lín Producto,Numero articulo,Descripción,UM,Cnt Requerd,Cantidad,Lote/Serie,Almacén,Ubicación
0,2026-01-31,RCT-TR,NaN,7,1325,Mycofix plus,kg,0.000000,1000.000000,LS-BI00002091,PIFCA,PIFCA
1,2026-01-31,ISS-TR,NaN,7,1325,Mycofix plus,kg,0.000000,-1000.000000,LS-BI00002091,CINTA,TRANSITO
2,2026-01-31,CST-ADJ,NaN,7,1325,Mycofix plus,kg,1000.000000,0.000000,NaN,PIFCA,NaN
3,2026-01-31,RCT-TR,NaN,15,PICHALMTO,Almto Pichidegua POSTURA,KG,0.000000,3100.000000,PICH5ACO,PICH5ACO,PIFCA
4,2026-01-31,ISS-TR,NaN,15,PICHALMTO,Almto Pichidegua POSTURA,KG,0.000000,-3100.000000,PICH5ACO,PIFCA,PIFCA
5,2026-01-31,CST-ADJ,NaN,15,PICHALMTO,Almto Pichidegua POSTURA,KG,3100.000000,0.000000,NaN,PICH5ACO,NaN
6,2026-01-31,RCT-WO,2047400,15,PICHALMTO,Almto Pichidegua POSTURA,KG,3100.000000,3100.000000,PICH5ACO,PIFCA,PIFCA
7,2026-01-31,ISS-WO,2047400,7,1409,DIGESTFAST,KG,3.100000,-3.100000,NaN,PIFCA,PIFCA
8,2026-01-31,ISS-WO,2047400,7,1406,ROVIMIX YOLK COLOR PRO,kg,1.405333,-1.405333,NaN,PIFCA,PIFCA
9,2026-01-31,ISS-WO,2047400,7,1396,Vitamina+Pigmento+Byd,kg,6.200000,-6.200000,NaN,PIFCA,PIFCA

## 2. Preprocesamiento y Limpieza de Datos
En esta sección se realizan las transformaciones necesarias para asegurar la integridad de los datos, incluyendo el filtrado de transacciones relevantes, el tratamiento de valores nulos en el Lote/Serie y la normalización de cantidades.

### 2.1. Filtrado de Movimientos: Consumo (ISS-WO) y Producción (RCT-WO)
Filtramos el dataset para quedarnos únicamente con las transacciones de salida de ingredientes y entrada de producto terminado, eliminando ruidos operativos del ERP.

In [8]:
# Definir los tipos de transacción que nos interesan
transacciones_interes = ['RCT-WO', 'ISS-WO']

# Filtrar el DataFrame para quedarnos solo con las filas que tengan los tipos de transacción deseados
df_alimento_filtrado = df_alimento_limpio[df_alimento_limpio['Tipo Trans'].isin(transacciones_interes)].copy()

# Validación de los datos filtrados
print(f"✅ Filtrado completado.")
print(f"Registros originales: {len(df_alimento_limpio)}")
print(f"Registros tras el filtro: {len(df_alimento_filtrado)}")
print(f"\nDistribución de transacciones en el nuevo set:")
print(df_alimento_filtrado['Tipo Trans'].value_counts())

# Mostrar los primeros resultados
display(df_alimento_filtrado.head())
df_alimento_filtrado.info()

✅ Filtrado completado.
Registros originales: 5570
Registros tras el filtro: 4486

Distribución de transacciones en el nuevo set:
Tipo Trans
ISS-WO    4121
RCT-WO     365
Name: count, dtype: int64

,Efectiva,Tipo Trans,Orden,Lín Producto,Numero articulo,Descripción,UM,Cnt Requerd,Cantidad,Lote/Serie,Almacén,Ubicación
6,2026-01-31,RCT-WO,2047400,15,PICHALMTO,Almto Pichidegua POSTURA,KG,3100.000000,3100.000000,PICH5ACO,PIFCA,PIFCA
7,2026-01-31,ISS-WO,2047400,7,1409,DIGESTFAST,KG,3.100000,-3.100000,NaN,PIFCA,PIFCA
8,2026-01-31,ISS-WO,2047400,7,1406,ROVIMIX YOLK COLOR PRO,kg,1.405333,-1.405333,NaN,PIFCA,PIFCA
9,2026-01-31,ISS-WO,2047400,7,1396,Vitamina+Pigmento+Byd,kg,6.200000,-6.200000,NaN,PIFCA,PIFCA
10,2026-01-31,ISS-WO,2047400,7,1338,Vitamina D3 HyD,kg,3.100000,-3.100000,NaN,PIFCA,PIFCA

<class 'pandas.core.frame.DataFrame'>
Index: 4486 entries, 6 to 5561
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Efectiva         4486 non-null   datetime64[ns]
 1   Tipo Trans       4486 non-null   object
 2   Orden            4486 non-null   object
 3   Lín Producto     4486 non-null   int64
 4   Numero articulo  4486 non-null   object
 5   Descripción      4486 non-null   object
 6   UM               4486 non-null   object
 7   Cnt Requerd      4486 non-null   float64
 8   Cantidad         4486 non-null   float64
 9   Lote/Serie       252 non-null    object
 10  Almacén          4486 non-null   object
 11  Ubicación        4486 non-null   object
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 455.6+ KB

### 2.2. Imputación de Valores Nulos (Forward Fill)
Los reportes del ERP agrupan visualmente los ingredientes omitiendo el nombre del lote en las filas secundarias. Aplicamos un "Forward Fill" para propagar el identificador del lote hacia abajo y asignar correctamente cada ingrediente a su orden de fabricación correspondiente.

In [11]:
# Comprobación inicial: ¿Cuantos valores nulos tenemos?
nulos_antes = df_alimento_filtrado['Lote/Serie'].isna().sum()
print(f"🔍 Valores nulos en 'Lote/Serie' antes de la limpieza: {nulos_antes}")

# Aplicar Forward Fill
# Sobrescribimos la columna con su versión rellenada hacia abajo
df_alimento_filtrado['Lote/Serie'] = df_alimento_filtrado['Lote/Serie'].ffill()

# Comprobación final
nulos_despues = df_alimento_filtrado['Lote/Serie'].isna().sum()
print(f"✅ Valores nulos en 'Lote/Serie' DESPUÉS de limpiar: {nulos_despues}")

# 4. Ver visualmente cómo quedó rellenado
display(df_alimento_filtrado.head(10))

🔍 Valores nulos en 'Lote/Serie' antes de la limpieza: 0
✅ Valores nulos en 'Lote/Serie' DESPUÉS de limpiar: 0

,Efectiva,Tipo Trans,Orden,Lín Producto,Numero articulo,Descripción,UM,Cnt Requerd,Cantidad,Lote/Serie,Almacén,Ubicación
6,2026-01-31,RCT-WO,2047400,15,PICHALMTO,Almto Pichidegua POSTURA,KG,3100.000000,3100.000000,PICH5ACO,PIFCA,PIFCA
7,2026-01-31,ISS-WO,2047400,7,1409,DIGESTFAST,KG,3.100000,-3.100000,PICH5ACO,PIFCA,PIFCA
8,2026-01-31,ISS-WO,2047400,7,1406,ROVIMIX YOLK COLOR PRO,kg,1.405333,-1.405333,PICH5ACO,PIFCA,PIFCA
9,2026-01-31,ISS-WO,2047400,7,1396,Vitamina+Pigmento+Byd,kg,6.200000,-6.200000,PICH5ACO,PIFCA,PIFCA
10,2026-01-31,ISS-WO,2047400,7,1338,Vitamina D3 HyD,kg,3.100000,-3.100000,PICH5ACO,PIFCA,PIFCA
11,2026-01-31,ISS-WO,2047400,7,1332,Sal Comun,kg,7.853333,-7.853333,PICH5ACO,PIFCA,PIFCA
12,2026-01-31,ISS-WO,2047400,7,1325,Mycofix plus,kg,2.170000,-2.170000,PICH5ACO,PIFCA,pifca
13,2026-01-31,ISS-WO,2047400,7,1324,Metionina polvo 99,kg,3.244667,-3.244667,PICH5ACO,PIFCA,PIFCA
14,2026-01-31,ISS-WO,2047400,7,1320,Lisina,kg,2.976000,-2.976000,PICH5ACO,PIFCA,PIFCA
15,2026-01-31,ISS-WO,2047400,7,1301,Antioxidante,kg,1.550000,-1.550000,PICH5ACO,PIFCA,PIFCA