In [1]:
# Importar librerias
import os
import pandas as pd
import glob
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [13]:
# Configurar pandas para mostrar todas las columnas
pd.set_option('display.max_columns', None)

# 1. Ruta del archivo
ruta_Archivo = r'D:\crist\OneDrive\Estudios\Proyectos Para GitHub\avian-data-ml-pipeline\data\raw\Produccion\PRODUCCION_ENERO_2026.csv'

# 2. Leer el archivo con manejo de errores
try:
    # Leemos la pestaña correcta
    df_Produccion = pd.read_csv(ruta_Archivo, encoding='latin-1')  # Especificamos la codificación para evitar problemas con caracteres especiales  
    print(f"✅ Archivo leído correctamente: {ruta_Archivo}")
    print(f"📊 Total de filas cargadas: {len(df_Produccion)}\n")
    
    # 3. Ver los resultados (solo se ejecuta si el paso anterior funcionó)
    print("--- Información del DataFrame ---")
    df_Produccion.info()

    print("\n--- Primeras filas del DataFrame ---")
    display(df_Produccion.head())  # Usamos display para que se vea como tabla en Jupyter

except Exception as e:
    # Usamos ruta_Archivo en vez de df_Produccion para evitar el NameError
    print(f"❌ Error al intentar leer el archivo en {ruta_Archivo}: {e}")

✅ Archivo leído correctamente: D:\crist\OneDrive\Estudios\Proyectos Para GitHub\avian-data-ml-pipeline\data\raw\Produccion\PRODUCCION_ENERO_2026.csv
📊 Total de filas cargadas: 39102

--- Información del DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39102 entries, 0 to 39101
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Fcha             39102 non-null  object
 1   Efectiva         39102 non-null  object
 2   Hora             39102 non-null  object
 3   Núm tran         39102 non-null  int64
 4   Program          39102 non-null  object
 5   ID del Usuario   39102 non-null  object
 6   Tipo Trans       39102 non-null  object
 7   Orden            23433 non-null  object
 8   Lín.             39102 non-null  int64
 9   Observs          0 non-null      float64
 10  Ventas/Trabajo   0 non-null      float64
 11  ID               32623 non-null  object
 12  Dirección        0 non-null      float64
 13  Lín Producto     39102 non-null  int64
 14  Numero articulo  39102 non-null  object
 15  Descripción      39102 non-null  object
 16  UM               39102 non-null  object
 17  Cnt Requerd      39102 non-null  object
 18  Cantidad         39102 non-null  object
 19  Prec             39102 non-null  object
 20  Moneda           39102 non-null  object
 21  PxQ              39102 non-null  object
 22  Monto Contable   39102 non-null  object
 23  CuMaterial       39102 non-null  object
 24  Lote/Serie       19981 non-null  object
 25  Referencia       133 non-null    object
 26  Almacén          39102 non-null  object
 27  Ubicación        32623 non-null  object
 28  Peso Embarq      39102 non-null  object
 29  Peso Neto        39102 non-null  object
 30  CE180            39102 non-null  object
 31  Site Origen      6444 non-null   object
 32  Ubic Origen      6444 non-null   object
dtypes: float64(3), int64(3), object(27)
memory usage: 9.8+ MB

--- Primeras filas del DataFrame ---

,Fcha,Efectiva,Hora,Núm tran,Program,ID del Usuario,Tipo Trans,Orden,Lín.,Observs,Ventas/Trabajo,ID,Dirección,Lín Producto,Numero articulo,Descripción,UM,Cnt Requerd,Cantidad,Prec,Moneda,PxQ,Monto Contable,CuMaterial,Lote/Serie,Referencia,Almacén,Ubicación,Peso Embarq,Peso Neto,CE180,Site Origen,Ubic Origen
0,02-02-2026,31-01-2026,13:51:26,28406779,wobkfl.p,BODPICH,RCT-WO,2047758,0,NaN,NaN,5758178,NaN,19,4041,Huevo Color sin Clasif,un,"3.030,0","3.030,0","54,03",CLP,"163.708,00","163.708,00","51,90",CAP1A,NaN,CAP1A,VIRTUP1A,"1,00","1,00","16,83",NaN,NaN
1,02-02-2026,31-01-2026,13:51:26,28406778,wobkfl.p,BODPICH,ISS-WO,2047758,0,NaN,NaN,5758178,NaN,15,PICHALMTO,Almto Pichidegua POSTURA,KG,"0,0","-563,0","290,78",CLP,"-163.707,94","163.708,00","290,78",CAP1A,NaN,CAP1A,CASILP1A,"0,00","1,00",",00",NaN,NaN
2,02-02-2026,31-01-2026,13:49:08,28406777,wobkfl.p,BODPICH,RCT-WO,2047757,0,NaN,NaN,5758177,NaN,19,4028,Huevo Sucio color x 30,un,"1,0","1,0","1.463,00",CLP,"1.463,00","1.463,00","1.463,00",CAP1B,NaN,CAP1B,VIRTUP1A,"30,00","1,00",",17",NaN,NaN
3,02-02-2026,31-01-2026,13:49:08,28406775,wobkfl.p,BODPICH,ISS-WO,2047757,0,NaN,NaN,5758177,NaN,19,4041,Huevo Color sin Clasif,un,"30,0","-30,0","46,84",CLP,"-1.405,13","1.405,00","46,84",CAP1B,NaN,CAP1B,VIRTUP1A,"1,00","1,00",",17",NaN,NaN
4,02-02-2026,31-01-2026,13:49:08,28406774,wobkfl.p,BODPICH,ISS-WO,2047757,0,NaN,NaN,5758177,NaN,5,3043,Tabique x 30,un,"1,0","-1,0","58,14",CLP,"-58,14","58,00","58,14",NaN,NaN,CAP1B,CAP1B,"0,00","1,00",",00",NaN,NaN

### Limpieza de nombres de columnas

In [14]:
df_Produccion.columns = (
    df_Produccion.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('.', '', regex=False)
    .str.normalize('NFKD')
    .str.encode('ascii', errors='ignore')
    .str.decode('utf-8')
)

df_Produccion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39102 entries, 0 to 39101
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fcha             39102 non-null  object
 1   efectiva         39102 non-null  object
 2   hora             39102 non-null  object
 3   num_tran         39102 non-null  int64
 4   program          39102 non-null  object
 5   id_del_usuario   39102 non-null  object
 6   tipo_trans       39102 non-null  object
 7   orden            23433 non-null  object
 8   lin              39102 non-null  int64
 9   observs          0 non-null      float64
 10  ventas/trabajo   0 non-null      float64
 11  id               32623 non-null  object
 12  direccion        0 non-null      float64
 13  lin_producto     39102 non-null  int64
 14  numero_articulo  39102 non-null  object
 15  descripcion      39102 non-null  object
 16  um               39102 non-null  object
 17  cnt_requerd      39102 non-null  object
 18  cantidad         39102 non-null  object
 19  prec             39102 non-null  object
 20  moneda           39102 non-null  object
 21  pxq              39102 non-null  object
 22  monto_contable   39102 non-null  object
 23  cumaterial       39102 non-null  object
 24  lote/serie       19981 non-null  object
 25  referencia       133 non-null    object
 26  almacen          39102 non-null  object
 27  ubicacion        32623 non-null  object
 28  peso_embarq      39102 non-null  object
 29  peso_neto        39102 non-null  object
 30  ce180            39102 non-null  object
 31  site_origen      6444 non-null   object
 32  ubic_origen      6444 non-null   object
dtypes: float64(3), int64(3), object(27)
memory usage: 9.8+ MB

### Dejar solamente las columnas a utilizar o utiles

In [15]:
# 1. Definir una lista con los nombres de las columnas que necesitams
columnas_utiles = [
    'efectiva',
    'lin_producto',
    'tipo_trans',
    'numero_articulo',
    'um',
    'cantidad',
    'lote/serie',
    'almacen',
    'ubicacion'
]

# 2. Aplicar el filtro al DataFrame
df_Produccion_filtrado = df_Produccion[columnas_utiles]

# 3. Validar resultado
print(f"✅ Reducción exitosa: Pasamos de {len(df_Produccion.columns)} columnas a solo {len(df_Produccion_filtrado.columns)}.")
print("--- Nueva estructura del DataFrame ---")
display(df_Produccion_filtrado.head())

✅ Reducción exitosa: Pasamos de 33 columnas a solo 9.
--- Nueva estructura del DataFrame ---

,efectiva,lin_producto,tipo_trans,numero_articulo,um,cantidad,lote/serie,almacen,ubicacion
0,31-01-2026,19,RCT-WO,4041,un,"3.030,0",CAP1A,CAP1A,VIRTUP1A
1,31-01-2026,15,ISS-WO,PICHALMTO,KG,"-563,0",CAP1A,CAP1A,CASILP1A
2,31-01-2026,19,RCT-WO,4028,un,"1,0",CAP1B,CAP1B,VIRTUP1A
3,31-01-2026,19,ISS-WO,4041,un,"-30,0",CAP1B,CAP1B,VIRTUP1A
4,31-01-2026,5,ISS-WO,3043,un,"-1,0",NaN,CAP1B,CAP1B

## 2. Preprocesamiento y Limpieza de Datos
En esta sección se realizan las transformaciones necesarias para asegurar la integridad de los datos, incluyendo el filtrado de transacciones relevantes, el tratamiento de valores nulos en el Lote/Serie y la normalización de cantidades.

### 2.1. Filtrado de Movimientos: Consumo (ISS-WO) y Producción (RCT-WO)
Filtramos el dataset para quedarnos únicamente con las transacciones de salida y entrada de producto terminado, eliminando ruidos operativos del ERP.

In [16]:
# Definir las transformaciones de interes
transacciones_interes = ['RCT-WO', 'ISS-WO']

# Filtrar el DataFrame para quedarnos solo con las transacciones de interes
df_Produccion_filtrado = df_Produccion_filtrado[df_Produccion_filtrado['tipo_trans'].isin(transacciones_interes)]

# Validación de los datos filtrados
print(f"✅ Filtrado completado.")
print(f"Registro originales: {len(df_Produccion)} | Registros después del filtro: {len(df_Produccion_filtrado)}")
print(f"\nDistribución de las transacciones filtradas:")
print(df_Produccion_filtrado['tipo_trans'].value_counts())

# mostrar las primeras filas del DataFrame filtrado
df_Produccion_filtrado.info()
display(df_Produccion_filtrado.head())

✅ Filtrado completado.
Registro originales: 39102 | Registros después del filtro: 18977

Distribución de las transacciones filtradas:
tipo_trans
ISS-WO    13379
RCT-WO     5598
Name: count, dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 18977 entries, 0 to 38624
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   efectiva         18977 non-null  object
 1   lin_producto     18977 non-null  int64
 2   tipo_trans       18977 non-null  object
 3   numero_articulo  18977 non-null  object
 4   um               18977 non-null  object
 5   cantidad         18977 non-null  object
 6   lote/serie       11209 non-null  object
 7   almacen          18977 non-null  object
 8   ubicacion        18977 non-null  object
dtypes: int64(1), object(8)
memory usage: 1.4+ MB

,efectiva,lin_producto,tipo_trans,numero_articulo,um,cantidad,lote/serie,almacen,ubicacion
0,31-01-2026,19,RCT-WO,4041,un,"3.030,0",CAP1A,CAP1A,VIRTUP1A
1,31-01-2026,15,ISS-WO,PICHALMTO,KG,"-563,0",CAP1A,CAP1A,CASILP1A
2,31-01-2026,19,RCT-WO,4028,un,"1,0",CAP1B,CAP1B,VIRTUP1A
3,31-01-2026,19,ISS-WO,4041,un,"-30,0",CAP1B,CAP1B,VIRTUP1A
4,31-01-2026,5,ISS-WO,3043,un,"-1,0",NaN,CAP1B,CAP1B